language: node_js

dist: trusty
sudo: false

node_js:
  - 'node'

install:
  - yarn

script:
  - npx raml2html --theme raml2html-modern-theme -o ./index.html -i ./api.raml

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
