#%RAML 1.0
title: Efficient Masturbation With Aggregated Search
description: "emwas is a meta search engine that gather searches from different porn sites and display them into one only convivial interface. It allows you to find the porn you're looking for faster and gives you the direct link to the original videos. It is for now intended to work with a limited number of non-free big porn websites"
version: 1.0
protocols:
  - https
baseUri: https://api.emwas.co
/services:
  description: A module to list available services in the current state of the API.
  get:
    description: Get all the different services (porn sites) that you can search on.
    responses:
      200:
        body:
          application/json:
            properties:
              id:
                type: number
                description: The id of the service
              name:
                type: string
                description: The common / canonical name of the website
              baseUrl:
                type: string
                description: The URL where you can found this website
            example: !include examples/services/servicesList.json
      500:
        body:
          application/json:
            example: !include examples/errors/serverError.json

/search:
  description: |
    The main module of the application.
    Perform a search on the pornsites that are availables / wanted by the user.
  get:
    description: Performs a search on all the services and get a list of videos from that.
    queryParameters:
      q:
        type: string
        required: true
        description: |
          The free text search you would type on your porn site search engine.
          All porn site handle very well pornstar names.
          Some also finds pretty well if you type a category or something else.
        example: "Alex%20Grey"
    responses:
      200:
        body:
          application/json:
            properties:
              title:
                description: The title of the scene.
                type: string
              url:
                description: The url of the scene on its original website.
                type: uri (string)
              thumbnailUrl:
                description: The list of thumbnail for the scenes on the original website.
                type: array [uri (string)]
                required: false
              performers:
                description: |
                  The list of the performer names declared on the scene by the original website.
                  Guys are sometimes not declared by the sites (which is a pity), so you won't always have them.
                type: array (string)
                required: false
              description:
                description: |
                  The description of the scene by the original website.
                  Might be very long depending on the service and the scene.
                type: string
                required: false
              date:
                description: The date the scene was posted. The format is the standard Javascript ISO8601 format.
                type: date
              length:
                description: |
                  The length of the video in seconds.
                  Might not be extremely precise depending on the website since some of them display video length in minutes.
                type: integer
                required: false
            example: !include examples/search/searchResult.json
      500:
        body:
          application/json:
            example: !include examples/errors/serverError.json
